name: PKGBUILD CI

on: [push, pull_request]

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Makepkg Build and Check
      id: makepkg
      uses: edlanglois/pkgbuild-action@v1
    - name: Print Package Files
      run: |
        echo "Successfully created the following package archive"
        echo "Package: ${{ steps.makepkg.outputs.pkgfile0 }}"
    # Uncomment to upload the package as an artifact
    # - name: Upload Package Archive
    #   uses: actions/upload-artifact@v2
    #   with:
    #     path: ${{ steps.makepkg.outputs.pkgfile0 }}
inputs:
  pkgdir:
    description: "Relative path to directory containing the PKGBUILD file."
    required: false
    default: "."
  makepkgArgs:
    description: "Additional arguments to pass to makepkg."
    required: true
    default: "-s  --skippgpcheck -f"